version: '3'
services:
    swagger-ui:
        ports:
          - 8080:8080
        image: swaggerapi/swagger-ui
        restart: always
        volumes:
          - .:/usr/share/nginx/html/api
        environment:
                URLS: "[{ url: \"./api/aicon_um-swagger.json\", name: \"UserManagement\" },
                        { url: \"./api/aicon_dm-swagger.json\", name: \"DeviceManagement\" },
                       ]"