apiVersion: v1
entries:
  memphis:
  - apiVersion: v2
    appVersion: 1.1.1
    created: "2023-07-18T15:50:54.605102+03:00"
    description: Memphis.dev Helm chart
    digest: f557dcaf1fbf21fe2fd5ae7ee28a1a5a3c149c9e78c1a16ebdcb9bd5cf9117e5
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-1.1.1.tgz
    version: 1.1.1
