import { type Metadata } from "next";
import localFont from "next/font/local";
import { cn } from "@/lib/utils";
import { Indicator } from "@/components/indicator";
import "./globals.css";
import { Header } from "@/components/header";
import { ThemeProvider } from "@/components/theme-provider";

const fontSans = localFont({
  src: [
    { path: "../../public/fonts/Inter.var.woff2", style: "normal" },
    { path: "../../public/fonts/Inter-italic.var.woff2", style: "italic" },
  ],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          {children}
          <Indicator />
        </ThemeProvider>
      </body>
    </html>
  );
}
