import { type Metadata } from "next";
import localFont from "next/font/local";
import { cn } from "@/lib/utils";
import { Indicator } from "@/components/indicator";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";

const fontSans = localFont({
  src: [
    { path: "../../public/fonts/Inter.var.woff2", style: "normal" },
    { path: "../../public/fonts/Inter-italic.var.woff2", style: "italic" },
  ],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
          <Indicator />
        </ThemeProvider>
      </body>
    </html>
  );
}
