CREATE TABLE IF NOT EXISTS reviews(
    rid BIGSERIAL PRIMARY KEY,
    uid BIGSERIAL NOT NULL,
    cid BIGSERIAL NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at BIGINT NOT NULL DEFAULT NOW(),
    updated_at BIGINT NOT NULL DEFAULT NOW(),
)