apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-postgres-configmap
data:
  postgres-dbname: todo-db

---

apiVersion: v1
kind: Secret
metadata:
  name: todo-postgres-secret
type: Opaque
data:
  postgres-root-username: cm9vdA== # root
  postgres-root-password: cGFzc3dvcmQ= # password

---

apiVersion: v1
kind: Service
metadata:
  name: todo-postgres
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: todo-postgres

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-persistent-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /Users/tendon/repos/soft-arch-infra/example-service/data
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-persistent-volume-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-postgres
  template:
    metadata:
      labels:
        app: todo-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:11
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: todo-postgres-secret
                  key: postgres-root-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-postgres-secret
                  key: postgres-root-password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: todo-postgres-configmap
                  key: postgres-dbname
          volumeMounts:
            - name: my-volume
              mountPath: /data
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: my-persistent-volume-claim