apiVersion: v1
kind: Service
metadata:
  name: example-app
spec:
  ports:
    - port: 8080
  selector:
    app: example-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: tendont52/example-service:1.0.1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
      
