FROM golang:latest as builder
RUN mkdir /app
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
RUN mkdir /app
WORKDIR /app
COPY --from=builder /app/main .
COPY --from=builder /app/templates ./templates
COPY --from=builder /app/templates-company-approve ./templates-company-approve
COPY --from=builder /app/templates-company-reject ./templates-company-reject
EXPOSE 8080
CMD ["./main"]