- name: Disable swap
  command: swapoff -a

- name: Set overlay fs and br_netfilter to load on boot
  copy:
    dest: "/etc/modules-load.d/k8s.conf"
    content: |
      overlay
      br_netfilter

- name: Load overlay fs
  command: modprobe overlay

- name: Load br_netfilter
  command: modprobe br_netfilter

- name: Set sysctl values for k8s networking
  copy:
    dest: "/etc/sysctl.d/k8s.conf"
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1

- name: Reload sysctl
  command: sysctl --system

- name: Update repository index
  apt:
    update_cache: yes

- name: Install the newest versions of outdate packages
  apt:
    upgrade: dist
