apiVersion: v1
kind: Service
metadata:
    name: review-service
spec:
    ports:
        - port: 8080
          targetPort: 8080
    selector:
        app: review-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: review-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: review-service
    template:
        metadata:
            labels:
                app: review-service
        spec:
            containers:
                - name: review-service
                  image: {{ .Values.image }}
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8080
                  volumeMounts:
                      - mountPath: "/app/app.env"
                        subPath: app.env
                        name: dot-env-file
                        readOnly: true
            volumes:
                - name: dot-env-file
                  secret:
                      secretName: review-service
