apiVersion: v1
kind: Service
metadata:
  name: report-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: report-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
        - name: report-service
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/app/app.env"
              subPath: app.env
              name: dot-env-file
              readOnly: true
      volumes:
        - name: dot-env-file
          secret:
            secretName: report-service